package com.butterflymovies.butterflymovies.models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Renting implements Serializable{
	
	/**
	 * Generated by eclipse. This keeps everybody happy! 
	 */
	private static final long serialVersionUID = 5530837988124322848L;
	
	@Id
	@GeneratedValue(strategy= GenerationType.AUTO)
	private long id;
	
	private int movieId;
	private int userId;
	private String start, devolution;
	
	
	//is it necessary to create gets returning a User and a Movie?		

	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public int getMovieId() {
		return movieId;
	}
	public void setMovieId(int movieId) {
		this.movieId = movieId;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getStart() {
		return start;
	}
	public void setStart(String start) {
		this.start = start;
	}
	public String getDevolution() {
		return devolution;
	}
	public void setDevolution(String devolution) {
		this.devolution = devolution;
	}		
	
}
