package com.butterflymovies.butterflymovies.models;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class User implements Serializable {
	/**
	 * Automatically generated by eclipse.
	 */
	private static final long serialVersionUID = -7733053823059245065L;
	
	@Id
	@GeneratedValue(strategy= GenerationType.AUTO)
	private long cod;
	
	private String name;
	private String gender;
	private String cpf;
	
//	@OneToMany
//	private List<Renting> rents;			//rents made by the user;
	
	
	public long getCod() {
		return cod;
	}
	public void setCod(long cod) {
		this.cod = cod;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	public String getCpf() {
		return cpf;
	}
	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

}
